name: AOS-ktlint
on:
  pull_request:
    branches:
      - AOS-develop
      - AOS-*/**
  push:
    paths:
      - '**.kt'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: Run ktlint
      run: cd AOS && chmod +x ./gradlew &&./gradlew ktlintCheck
      
